project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd

website:
  title: "gpt-nano"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



