project:
  type: website
  output-dir: docs
  render: 
    - pages/*.qmd
    - slides/demo-1.qmd

website:
  title: "GPT is Not An Oracle"
  site-url: https://virtuelleakademie.github.io/gpt-nano
  repo-url: https://github.com/virtuelleakademie/gpt-nano
  # repo-actions: [edit, issue]
  favicon: /assets/robot.png
  open-graph: true
  search: 
    location: navbar
    type: overlay
    # type: textbox
  twitter-card:
    creator: "@awellis"
    card-style: summary_large_image

  reader-mode: true
  back-to-top-navigation: true
  navbar:
    logo: /assets/robot.png
    left:
      - text: "🏠 Home"
        file: pages/index.qmd

      - text: "🛠️ Resources"
        menu: 
          - text: "KI-basierte Schreibtools in der Lehre – ChatGPT im Fokus"
            file: pages/orientierungshilfe.qmd

      - text: "📚 Tutorials"
        menu: 
          - text: "What is ChatGPT?"
            file: pages/about.qmd
          - text: "How to think about GPT"
          - text: "What can GPT do?"
          - text: "Ethical concerns"
          - text: "Legal concerns"

      - text: "📺 Presentations"
        menu: 
          - text: "Informationsanlass Bibliotheksmitarbeitende"
            file: slides/demo-1.qmd
          - text: "Qualitätszirkel"
    # right: 
    #   - text: "About"
    #     file: pages/about.qmd

    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/virtuelleakademie/gpt-nano/
          - text: Report a Bug
            url:  https://github.com/virtuelleakademie/gpt-nano/issues

page-footer:
    right:
    - icon: github
      href: https://github.com/virtuelleakademie/gpt-nano/

format:
  html:
    theme:
      light:
      - cosmo
      # - styles/light.scss
      dark:
      - cosmo
      - styles/theme-dark.scss
    toc: true
    link-external-newwindow: true

execute:
  cache: true
  freeze: false
  execute-dir: project

editor:
  render-on-save: true
