---
title: "Program"
---
<!-- In this workshop, we will investigate how Large Language Models (LLMs) are trained, how they produce text, and what they are capable of. We will also discuss similarities and differences between LLMs and human thought processes. As LLMs become increasingly human-like in their performance, it is important to develop effective ways to describe their behaviour. We will discuss high-level concepts that allow us think about LLMs without falling into the trap of anthropomorphism. -->

## Inhalt

- Wie werden Large Language Models (LLMs) trainiert?
- Wie generieren LLMs Texte?
- Was sind Ähnlichkeiten und Unterschiede zwischen LLMs und menschlichem Denken?
- Wie können wir LLMs beschreiben, ohne sie zu anthropomorphisieren?

## Lernziele
:::{.callout-tip}
## Nach diesem Workshop:
1) Können Sie mit Anfragen von Studierenden in Bezug auf fach-spezifische AI-generierte Texte umgehen.
2) Können Sie in eigenen Worten wiedergeben, wie AI-generierte Texte entstehen.
3) Haben Sie Kriterien, anhand derer Sie KI-Tools beurteilen können.
:::

<!-- 
- Modell
- Zweck des Tools
- Zielgruppe
- Datenschutz
- Herausgeber + Preismodell
- Offenheit des Codes 
-->

## Program

```{mermaid}
flowchart LR
  A(["Einführung
            5'"]) 
  A -.-> B(["Reaktivationsrunde 
                      10'"]) 
  B -.-> C(["Input: Wie funktioniert ChatGPT? 
                      30'"])
  C -.-> D(["Vertiefung: Lernziele 1 + 2 
                      15'"]) 
  C -.-> E(["Vertiefung: Lernziel 3 
                        15'"]) 
  D -.-> F(["Ankern 
                30'"]) 
  E -.-> F
  F -.-> G(["Diskussion 
            20'"]) 
  G -.-> H[Ende]
```

- Welcome and introduction [5']
- Reaktivationsrunde [10']
- Input: What is ChatGPT and how does is work? [30']
- Vertiefung: How do you use ChatGPT? [30']
  - Think (2') - pair (3') - share (10')
- Ankern [5']
- Diskussion [20']


## Leitung

- [Andrew Ellis](https://www.bfh.ch/en/about-bfh/people/a3xvoqozosua/): 
Andrew ist Data Scientist an der [Virtuellen Akademie](https://virtuelleakademie.ch/) der [Berner Fachhochschule](https://www.bfh.ch/en/). Sein Hintergrund ist in den Kognitionswissenschaften und er ist begeistert von der Schnittstelle zwischen Sprache, Denken und künstlicher Intelligenz."

<!-- ## Tutorials

- [0: Instructions](instructions.qmd). Some instructions on the tools used in the workshop. It would be handy to read this before the workshop starts!
- [1: What is ChatGPT and how does is work?](pages/chatgpt.qmd). A brief introduction to the ChatGPT model, and how it works.
- [2: How do you use ChatGPT?](pages/prompting.qmd). A discussion of what can do, and how to use it correctly.
- [3: Concepts for thinking about ChatGPT](pages/concepts.qmd). A discussion of how to think about ChatGPT, and how it is similar and different to human thought. -->

<!-- ## Quick Start Guide

Qui exercitation voluptate aute Lorem veniam do amet consequat cillum culpa consectetur ea laboris. Dolor occaecat nisi nulla officia occaecat ut enim incididunt non nisi officia duis sint eu. Ad anim aute eu est. Laboris consequat voluptate veniam Lorem voluptate est. Veniam qui cillum nulla ex pariatur non ex nisi ut deserunt quis magna voluptate deserunt occaecat. In mollit ipsum cupidatat nostrud cupidatat ut eiusmod. -->


<!-- ```{mermaid}
journey
    %% title Program
    section Teil 1
      Einführung: 3: Andrew
    section Teil 2
      Reaktivationsrunde: 7: Teilnehmer
    section Teil 3
      Wie funktioniert ChatGPT?: 4: Andrew
    section Teil 4
      Lernziele 1 + 2: 7: Teilnehmer
      Lernziel 3: 7: Teilnehmer
    section Teil 5
      Ankern: 3: Andrew
    section Teil 6
      Diskussion: 7: Andrew, Teilnehmer
``` -->